config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'users/dashboard', to: 'users#dashboard'
  resources :learnings, only: [:index] do
    collection do
      post :search
    end
  end
  resources :questions, only: :show do
    resources :answers, only: :create
  end
  resources :rewards, only: :show
  resources :interests, only: :index
  resources :lecture, only: :show
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :learning
  has_many :options, dependent: :destroy
  has_many :answers, dependent: :destroy

  validates :content, presence: true

  def questions_left
    learning.questions.where('id > ?', id).count
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @question = Question.find(params[:id])
    @options = @question.options
    @answer = Answer.new
    @user_question_number = @question.questions_left
    # @learning = Learning.where(params[:id])
    # @questions = @learning.question.all
    # respond_to do |format|
    #   if @question.save
    #     format.html { redirect_to @question, notice: 'answer registered.' }
    #     format.json { redirect_to :new, status: :created, location: @question }
    #   else
    #     format.html { render :show }
    #     format.json { render json: @question.error, status: :unprocessable_entity }
    #   end
    # end
  end
end

app/views/questions/_choices.html.erb
<div class="banner-answers">
 <%= simple_form_for([@question, @answer]) do |f| %>
    <div class="event-listener" id='button'>
      <%= f.collection_radio_buttons :option, options.map {|option| [option.content, option.content]}, :first, :last do |b| %>
        <%= b.radio_button class: "radio-butt", data: { questions_target: 'radio', action: "click->questions#fill" } %>
        <%= b.label class:"labels", data: { questions_target: 'button' }%>
        <% end %>
    </div>
    <div class="quiz-buttons">
      <% if @question.learning.next_question(@question).present? %>
          <%= f.submit value: 'Suivant', class: "start-button" %>
      <% else %>
          <%= f.submit value: 'Terminer le quiz', class: "start-button" %>
      <% end %>
    </div>
 <% end %>
</div>

app/views/questions/_question.html.erb
<%= render "shared/progress_bar" %>
<div id="quiz-ask" data-id="<%= @question.answer_ids.count %>">
  <h3><%= @question.content %></h3>
</div>

app/views/questions/show.html.erb
<div class="container" id="quiz" data-controller="progress-bar questions" data-progress-bar-number-value = <%= @user_question_number %> data-progress-bar-total-value = <%= @question.learning.questions.count %>>
<% if @user_question_number > 0 %>
    <p id='little-info'><%= @user_question_number + 1 %> questions restantes !</p>
<% else %>
    <p id='little-info'>Dernière question !</p>
<% end %>
    <%= render 'questions/question', question: @question %>
    <%= render 'questions/choices', options: @options %>
  </div>
</div>