config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'users/dashboard', to: 'users#dashboard'
  resources :learnings, only: [:index] do
    collection do
      post :search
    end
  end
  resources :questions, only: :show do
    resources :answers, only: :create
  end
  resources :rewards, only: :show
  resources :interests, only: :index
  resources :lecture, only: :show
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="container inline-flex">
    <%= link_to root_path do %>
      <%= image_tag "logo-white.svg", alt: "Recyclearn" %>
    <% end %>
    <% if user_signed_in? %>
      <div class="avatar">
        <img src="https://avatars.githubusercontent.com/u/32631203?v=4 " alt="">
      </div>
      <%= button_to "logout", destroy_user_session_path, method: :delete  %>
    <% else %>
      <%= link_to "login",  user_session_path, class: "login-link-dark" %>
    <% end %>
  </div>
</header>

app/views/shared/_header_homepage.html.erb
<header>
  <div class="container-fluid inline-flex">
    <%= link_to root_path do%>
      <%= image_tag "logo.svg", alt: "Recyclearn" %>
    <% end %>
    <% if user_signed_in? %>
      <div class="avatar">
        <img src="https://avatars.githubusercontent.com/u/32631203?v=4 " alt="">
      </div>
      <%= button_to "logout", destroy_user_session_path, method: :delete  %>
    <% else %>
      <%= link_to "login",  user_session_path, class: "login-link" %>
    <% end %>
  </div>
  <div class="container-fluid">
    <p>Apprendre, comprendre et <br> pratiquer le recyclage.</p>
  </div>
</header>

app/views/shared/_learnings_filter.html.erb
<% unlocked_learnings.each do |learning| %>
  <%= link_to lecture_path(Lecture.where(learning_id: learning).first), class: "card-learnings" do %>
    <div>
      <div class="container-fluid">
        <%= image_tag "learnings/#{learning.title.downcase.gsub(/\s/, '_').gsub("é","e").gsub("è","e").gsub("à","a")}.jpg", alt: "#{learning.title.downcase.gsub(/\s/, '_')}" %>
      </div>

      <div class="container card-title">
        <div class="pill">
          <p><%= learning.title.capitalize %></p>
        </div>
      </div>

      <div class="learning-info">
        <div class="container">
          <p><i class="fa-solid fa-circle-question"></i> <%= learning.topic.capitalize %></p>
          <p><i class="fa-solid fa-gauge"></i> <%= learning.difficulty.capitalize %></p>
          <p><i class="fa-solid fa-leaf"></i> <%= learning.score  %></p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<% locked_learnings.each do |learning| %>
  <div class="card-learnings">
    <div class="locked-learning">

      <div class="container-fluid">
        <%= image_tag "learnings/#{learning.title.downcase.gsub(/\s/, '_').gsub("é","e").gsub("è","e").gsub("à","a")}.jpg", alt: "#{learning.title.downcase.gsub(/\s/, '_')}" %>
      </div>

      <div class="container card-title">
        <div class="pill">
          <p><%= learning.title.capitalize %></p>
        </div>
      </div>

      <div class="learning-info">
        <div class="container">
          <p><i class="fa-solid fa-circle-question"></i> <%= learning.topic.capitalize %></p>
          <p><i class="fa-solid fa-gauge"></i> <%= learning.difficulty.capitalize %></p>
          <p><i class="fa-solid fa-leaf"></i> <%= learning.score  %></p>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
  <%= link_to(root_path) do %>
    <i class="fa-solid fa-house"></i>
  <% end %>
  <%= link_to(interests_path) do %>
    <i class="fa-solid fa-location-arrow"></i>
  <% end %>
  <%= link_to(users_dashboard_path) do %>
    <i class="fa-solid fa-user"></i>
  <% end %>
</nav>

app/views/shared/_progress_bar.html.erb
<div class="progress-bar">
  <div class="completed-pb" data-progress-bar-target="item"></div>
</div>