config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'users/dashboard', to: 'users#dashboard'
  resources :learnings, only: [:index] do
    collection do
      post :search
    end
  end
  resources :questions, only: :show do
    resources :answers, only: :create
  end
  resources :rewards, only: :show
  resources :interests, only: :index
  resources :lecture, only: :show
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :learning
  has_rich_text :content

  validates :title, presence: true
end

app/controllers/lecture_controller.rb
class LectureController < ApplicationController
  def show
    @lecture = Lecture.find(params[:id])
    @learning = @lecture.learning
  end
end

app/views/lecture/show.html.erb
<div class="rich-card">

<%= @lecture.content %>
</div>
<br>
<div class="start">
  <div>
    <% if @learning.lectures.where('id < ?', @lecture.id).present? %>
      <%= link_to "Chapitre précédent", lecture_path(@learning.lectures.where('id < ?', @lecture.id).last), class:"start-button" %>
    <% else %>
      <%= link_to "Revenir aux leçons", learnings_path, class:"start-button" %>
    <% end %>
  </div>
  <div>
    <% if @learning.lectures.where('id > ?', @lecture.id).present? %>
      <%= link_to "Chapitre suivant", lecture_path(@learning.lectures.where('id > ?', @lecture.id).first), class:"start-button" %>
    <% else %>
      <%= link_to "Commencez le quiz", question_path(@learning.questions.first), class:"start-button" %>
    <% end %>
  </div>
</div>
<br><br><br><br><br><br>